apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: aks-cluster-rg
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  providerConfigRef:
    name: azure-default
  forProvider:
    location: East Asia
    tags:
      provisioner: crossplane