apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: main
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: azure-default
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: East Asia
    resourceGroupNameRef:
      name: aks-cluster-rg
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dmz-subnet-a
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  providerConfigRef:
    name: azure-default
  forProvider:
    addressPrefixes:
      - 10.0.1.0/24
    resourceGroupNameRef:
      name: aks-cluster-rg
    virtualNetworkNameRef:
      name: main
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dmz-subnet-b
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  providerConfigRef:
    name: azure-default
  forProvider:
    addressPrefixes:
      - 10.0.2.0/24
    resourceGroupNameRef:
      name: aks-cluster-rg
    virtualNetworkNameRef:
      name: main
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-a
  labels:
    tier: private
    subnet: a
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  providerConfigRef:
    name: azure-default
  forProvider:
    addressPrefixes:
      - 10.0.3.0/24
    resourceGroupNameRef:
      name: aks-cluster-rg
    virtualNetworkNameRef:
      name: main
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-b
  labels:
    tier: private
    subnet: b
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  providerConfigRef:
    name: azure-default
  forProvider:
    addressPrefixes:
      - 10.0.4.0/24
    resourceGroupNameRef:
      name: aks-cluster-rg
    virtualNetworkNameRef:
      name: main