apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: kyverno
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: "3.2.5"
    helm:
      releaseName: kyverno
      valuesObject:
        admissionController:
          replicas: 1
        backgroundController:
          replicas: 1
        cleanupController:
          replicas: 1
        reportsController:
          replicas: 1
        crds:
          migration:
            enabled: true
            resources:
              - admissionreports.kyverno.io
              - backgroundscanreports.kyverno.io
              - cleanuppolicies.kyverno.io
              - clusteradmissionreports.kyverno.io
              - clusterbackgroundscanreports.kyverno.io
              - clustercleanuppolicies.kyverno.io
              - clusterpolicies.kyverno.io
              - globalcontextentries.kyverno.io
              - policies.kyverno.io
              - policyexceptions.kyverno.io
              - updaterequests.kyverno.io
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
