apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:nhd1207/argocd-crossplane.git
  - https://charts.crossplane.io/stable
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'