apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: crossplane
  source:
    chart: crossplane-stable/crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.15.2
    helm:
      releaseName: crossplane
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true